// components
import Meta from '../components/Meta'
import Header from '../components/Header';
import Footer from '../components/Footer'
import Link from 'next/link'

const para1 = "Welcome to the Hyperscale website (including all subdomains and community communications systems, the “Site”), which is operated by [Corporate Entity] and its affiliates (collectively, “Hyperscale”, “Company”, “we”, “us” and/or “our”). Certain features of the Site may be subject to additional privacy policies, guidelines, terms, or rules, which will be posted on the Site in connection with such features. All such additional terms, guidelines, and rules are incorporated by reference into these Terms."
const para2 = "THESE TERMS OF USE (THESE “TERMS”) SET FORTH THE LEGALLY BINDING TERMS AND CONDITIONS THAT GOVERN YOUR USE OF THE SITE. BY ACCESSING OR USING THE SITE, YOU ARE ACCEPTING THESE TERMS (ON BEHALF OF YOURSELF OR THE ENTITY THAT YOU REPRESENT), AND YOU REPRESENT AND WARRANT THAT YOU HAVE THE RIGHT, AUTHORITY, AND CAPACITY TO ENTER INTO THESE TERMS (ON BEHALF OF YOURSELF OR THE ENTITY THAT YOU REPRESENT). YOU MAY NOT ACCESS OR USE THE SITE OR ACCEPT THE TERMS IF YOU ARE NOT AT LEAST 18 YEARS OLD. IF YOU DO NOT AGREE WITH ALL OF THE PROVISIONS OF THESE TERMS, DO NOT ACCESS AND/OR USE THE SITE."
const para3 = "THESE TERMS REQUIRE THE USE OF ARBITRATION ON AN INDIVIDUAL BASIS TO RESOLVE DISPUTES, RATHER THAN JURY TRIALS OR CLASS ACTIONS, AND ALSO LIMIT THE REMEDIES AVAILABLE TO YOU IN THE EVENT OF A DISPUTE"
const para4 = "Accounts and Use of the Site"
const para5 = "Account Creation: In order to use certain features of the Site, you may be required to register for an account (“Account”) and provide certain information about yourself as prompted by the account registration process. You represent and warrant that: (a) all required registration information you submit is truthful and accurate; (b) you will maintain the accuracy of such information. Registration data and certain other information about you are also governed by our privacy policies. Company may suspend or terminate your Account in accordance with these Terms."
const para6 = "Account Responsibilities: You are responsible for maintaining the confidentiality of your Account login information and are fully responsible for all activities that occur under your Account. You agree to immediately notify the Company of any unauthorized use, or suspected unauthorized use of your Account or any other breach of security. Company cannot and will not be liable for any loss or damage arising from your failure to comply with the above requirements."
const para7 = "Site License: Subject to these Terms, Company grants you a non-transferable, non-exclusive, revocable, limited license to use and access the Site solely for your own personal, noncommercial use. The rights granted to you in these Terms are subject to the following restrictions: (a) you shall not license, sell, rent, lease, transfer, assign, distribute, host, or otherwise commercially exploit the Site, whether in whole or in part, or any content displayed on the Site; (b) you shall not modify, make derivative works of, disassemble, reverse compile or reverse engineer any part of the Site; (c) you shall not access the Site in order to build a similar or competitive website, product, or service; and (d) except as expressly stated herein, no part of the Site may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means. Unless otherwise indicated, any future release, update, or other addition to functionality of the Site shall be subject to these Terms. All copyright and other proprietary notices on the Site (or on any content displayed on the Site) must be retained on all copies thereof."
const para8 = "Modifications: Company reserves the right, at any time, to modify, suspend, or discontinue the Site (in whole or in part) with or without notice to you. You agree that the Company will not be liable to you or to any third party for any modification, suspension, or discontinuation of the Site or any part thereof. Certain experimental portions of the Site, including but not limited to the DAO Race, may be subject to frequent interventions and modifications intended to improve the Service and/or protect the integrity or reliability of the Service."
const para9 = "Support: You acknowledge and agree that the Company will have no obligation to provide you with any support or maintenance in connection with the Site."
const para10 = "General Practices Regarding Use and Storage: You acknowledge that Company may establish general practices and limits concerning use of the Site, including without limitation the maximum period of time that data or other content will be retained by the Site and the maximum storage space that will be allotted on Company’s servers on your behalf. You agree that the Company has no responsibility or liability for the deletion or failure to store any data or other content maintained or uploaded by the Site. You acknowledge that the Company reserves the right to terminate accounts that are inactive for an extended period of time. You further acknowledge that the Company reserves the right to change these general practices and limits at any time, in its sole discretion, with or without notice."
const para11 = "Conditions of Use"
const para12 = "In addition to any applicable guidelines or policies that may govern specific components of the Site, you agree to comply with the following conditions in using the Site. You are solely responsible for all code, video, images, information, data, text, software, music, sound, photographs, graphics, messages or other materials (“User Content”) that you upload, post, publish or display (hereinafter, “upload”) or email or otherwise transmit via the Site."
const para13 = "You assume all risks associated with use of your User Content, including any reliance on its accuracy, completeness or usefulness by others, or any disclosure of your User Content that personally identifies you or any third party. You hereby represent and warrant that your User Content does not violate this provision. You may not represent or imply to others that your User Content is in any way provided, sponsored or endorsed by the Company. Because you alone are responsible for your User Content, you may expose yourself to liability if, for example, your User Content violates this provision. Company is not obligated to backup any User Content, and your User Content may be deleted at any time without prior notice. You are solely responsible for creating and maintaining your own backup copies of your User Content if you desire. Additionally, you hereby grant (and you represent and warrant that you have the right to grant) to Company an irrevocable, nonexclusive, royalty-free and fully paid, worldwide license to reproduce, distribute, publicly display and perform, prepare derivative works of, incorporate into other works, and otherwise use and exploit your User Content, and to grant sublicenses of the foregoing rights, solely for the purposes of including your User Content in the Site. You hereby irrevocably waive (and agree to cause to be waived) any claims and assertions of moral rights or attribution with respect to your User Content."
const para14 = "You agree not to use the Site to collect, upload, transmit, display, or distribute any content (i) that violates any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right; (ii) that is unlawful, harassing, abusive, tortious, threatening, harmful, invasive of another’s privacy, vulgar, defamatory, false, intentionally misleading, trade libelous, pornographic, obscene, patently offensive, promotes racism, bigotry, hatred, or physical harm of any kind against any group or individual or is otherwise objectionable; (iii) that is harmful to minors in any way; or (iv) that is in violation of any law, regulation, or obligations or restrictions imposed by any third party"
const para15 = "In addition, you agree not to: (i) upload, transmit, or distribute to or through the Site any computer viruses, worms, or any software intended to damage or alter a computer system or data; (ii) send through the Site unsolicited or unauthorized advertising, promotional materials, junk mail, spam, chain letters, pyramid schemes, or any other form of duplicative or unsolicited messages, whether commercial or otherwise; (iii) use the Site to harvest, collect, gather or assemble information or data regarding other users, including email addresses, without their consent; (iv) interfere with, disrupt, or create an undue burden on servers or networks connected to the Site, or violate the regulations, policies or procedures of such networks; (v) attempt to gain unauthorized access to the Site (or to other computer systems or networks connected to or used together with the Site), whether through password mining or any other means; (vi) harass or interfere with any other user’s use and enjoyment of the Site; or (vi) use software or automated agents or scripts to produce multiple accounts on the Site, or to generate automated searches, requests, or queries to (or to strip, scrape, or mine data from) the Site (provided, however, that we conditionally grant to the operators of public search engines revocable permission to use spiders to copy materials from the Site for the sole purpose of and solely to the extent necessary for creating publicly available searchable indices of the materials, but not caches or archives of such materials, subject to the parameters set forth in our robots.txt file); or (vii) unless otherwise expressly authorized herein of in the Site, display, distribute, license, perform, publish, reproduce, duplicate, copy, create derivative works from, modify, sell, resell, exploit, transfer or upload for any commercial purposes, any portion of the Site, use of the Site, or access to the Site."
const para16 = "We reserve the right (but have no obligation) to review any content, and to investigate and/or take appropriate action against you in our sole discretion if you violate this provision or any other provision of these Terms or otherwise create liability for us or any other person. Such action may include removing or modifying your User Content, terminating your Account in accordance with these Terms, and/or reporting you to law enforcement authorities."
const para17 = "Indemnification"
const para18 = "You agree to indemnify and hold Company (and its officers, employees, and agents) harmless, including costs and attorneys’ fees, from any claim or demand made by any third party due to or arising out of (a) your use of the Site, (b) your violation of these Terms, (c) your violation of applicable laws or regulations or (d) your User Content. Company reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate with our defense of these claims. You agree not to settle any matter without the prior written consent of the Company. Company will use reasonable efforts to notify you of any such claim, action or proceeding upon becoming aware of it."
const para19 = "Third-Party Links; Other Users"
const para20 = "Third-Party Links: The Site may contain links to third-party websites and services, and/or display advertisements for third parties (collectively, “ Third-Party Links”). Such Third-Party Links are not under the control of Company, and Company is not responsible for any Third-Party Links. Company provides access to these Third-Party Links only as a convenience to you, and does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third-Party Links. You use all Third-Party Links at your own risk, and should apply a suitable level of caution and discretion in doing so. When you click on any of the Third-Party Links, the applicable third party’s terms and policies apply, including the third party’s privacy and data gathering practices. You should make whatever investigation you feel necessary or appropriate before proceeding with any transaction in connection with such Third-Party Links."
const para21 = "Other Users: Each Site user is solely responsible for any and all of its own User Content. Because we do not control User Content, you acknowledge and agree that we are not responsible for any User Content, whether provided by you or by others. We make no guarantees regarding the accuracy, currency, suitability, or quality of any User Content. Your interactions with other Site users are solely between you and such users. You agree that the Company will not be responsible for any loss or damage incurred as the result of any such interactions. If there is a dispute between you and any Site user, we are under no obligation to become involved."
const para22 = "Release: You hereby release and forever discharge the Company (and our officers, employees, agents, successors, and assigns) from, and hereby waive and relinquish, each and every past, present and future dispute, claim, controversy, demand, right, obligation, liability, action and cause of action of every kind and nature (including personal injuries, death, and property damage), that has arisen or arises directly or indirectly out of, or that relates directly or indirectly to, the Site (including any interactions with, or act or omission of, other Site users or any Third-Party Links). IF YOU ARE A CALIFORNIA RESIDENT, YOU HEREBY WAIVE CALIFORNIA CIVIL CODE SECTION 1542 IN CONNECTION WITH THE FOREGOING, WHICH STATES: “A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM OR HER MUST HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR.”"
const para23 = "Disclaimers "
const para24 = "THE SITE IS PROVIDED ON AN “AS-IS” AND “AS AVAILABLE” BASIS, AND COMPANY (AND OUR SUPPLIERS) EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES AND CONDITIONS OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING ALL WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUIET ENJOYMENT, ACCURACY, OR NON-INFRINGEMENT.  WE (AND OUR SUPPLIERS) MAKE NO WARRANTY THAT THE SITE WILL MEET YOUR REQUIREMENTS, WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS, OR WILL BE ACCURATE, RELIABLE, FREE OF VIRUSES OR OTHER HARMFUL CODE, COMPLETE, LEGAL, OR SAFE.  IF APPLICABLE LAW REQUIRES ANY WARRANTIES WITH RESPECT TO THE SITE, ALL SUCH WARRANTIES ARE LIMITED IN DURATION TO NINETY (90) DAYS FROM THE DATE OF FIRST USE."
const para25 = "SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSION MAY NOT APPLY TO YOU.  SOME JURISDICTIONS DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU.  "
const para26 = "Limitation on Liability"
const para27 = "TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL COMPANY (OR OUR SUPPLIERS) BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY LOST PROFITS, LOST DATA, COSTS OF PROCUREMENT OF SUBSTITUTE PRODUCTS, OR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES ARISING FROM OR RELATING TO THESE TERMS OR YOUR USE OF, OR INABILITY TO USE, THE SITE, EVEN IF COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.  ACCESS TO, AND USE OF, THE SITE IS AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR DEVICE OR COMPUTER SYSTEM, OR LOSS OF DATA RESULTING THEREFROM.  "
const para28 = "TO THE MAXIMUM EXTENT PERMITTED BY LAW, NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, OUR LIABILITY TO YOU FOR ANY DAMAGES ARISING FROM OR RELATED TO THIS AGREEMENT (FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION), WILL AT ALL TIMES BE LIMITED TO A MAXIMUM OF FIFTY US DOLLARS (U.S. $50). THE EXISTENCE OF MORE THAN ONE CLAIM WILL NOT ENLARGE THIS LIMIT.  YOU AGREE THAT OUR SUPPLIERS WILL HAVE NO LIABILITY OF ANY KIND ARISING FROM OR RELATING TO THIS AGREEMENT."
const para29 = "SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU."
const para30 = "Term and Termination "
const para31 = "Subject to this Section, these Terms will remain in full force and effect while you use the Site.  We may suspend or terminate your rights to use the Site (including your Account) at any time for any reason at our sole discretion, including for any use of the Site in violation of these Terms.  Upon termination of your rights under these Terms, your Account and right to access and use the Site will terminate immediately.  You understand that any termination of your Account may involve deletion of your User Content associated with your Account from our live databases.  Company will not have any liability whatsoever to you for any termination of your rights under these Terms, including for termination of your Account or deletion of your User Content.  Termination of your account or access to any component of the Site will not terminate Company’s rights to your User Content or any other rights under these Terms. Further, you agree that the Company will not be liable to you or any third party for any termination of your access to the Site."
const para32 = "Copyright Policy"
const para33 = "Company respects the intellectual property of others and asks that users of our Site do the same.  In connection with our Site, we have adopted and implemented a policy respecting copyright law that provides for the removal of any infringing materials and for the termination, in appropriate circumstances, of users of our online Site who are repeat infringers of intellectual property rights, including copyrights.  If you believe that one of our users is, through the use of our Site, unlawfully infringing the copyright(s) in a work, and wish to have the allegedly infringing material removed, the following information in the form of a written notification (pursuant to 17 U.S.C. § 512(c)) must be provided to our designated Copyright Agent:"
const para34 = "your physical or electronic signature;"
const para35 = "identification of the copyrighted work(s) that you claim to have been infringed;"
const para36 = "identification of the material on our services that you claim is infringing and that you request us to remove;"
const para37 = "sufficient information to permit us to locate such material;"
const para38 = "your address, telephone number, and e-mail address;"
const para39 = "a statement that you have a good faith belief that use of the objectionable material is not authorized by the copyright owner, its agent, or under the law; and"
const para40 = "a statement that the information in the notification is accurate, and under penalty of perjury, that you are either the owner of the copyright that has allegedly been infringed or that you are authorized to act on behalf of the copyright owner."
const para41 = "Please note that, pursuant to 17 U.S.C. § 512(f), any misrepresentation of material fact (falsities) in a written notification automatically subjects the complaining party to liability for any damages, costs and attorney’s fees incurred by us in connection with the written notification and allegation of copyright infringement."
const para42 = ""
const para43 = "General"
const para44 = "Changes:  These Terms are subject to occasional revision, and if we make any substantial changes, we may notify you by sending you an e-mail to the last e-mail address you provided to us (if any), and/or by prominently posting notice of the changes on our Site.  You are responsible for providing us with your most current email address.  In the event that the last e-mail address that you have provided us is not valid, or for any reason is not capable of delivering to you the notice described above, our dispatch of the e-mail containing such notice will nonetheless constitute effective notice of the changes described in the notice.  Any changes to these Terms will be effective upon the earlier of thirty (30) calendar days following our dispatch of an email notice to you (if applicable) or thirty (30) calendar days following our posting of notice of the changes on our Site.  These changes will be effective immediately for new users of our Site.  Continued use of our Site following notice of such changes shall indicate your acknowledgement of such changes and agreement to be bound by the terms and conditions of such changes."
const para45 = "Dispute Resolution: This Dispute Resolution section is referred to in these Terms as the “Arbitration Agreement.” Please read this Arbitration Agreement carefully.  It is part of your contract with the Company and affects your rights.  It contains procedures for MANDATORY BINDING ARBITRATION AND A CLASS ACTION WAIVER."
const para46 = "Applicability of Arbitration Agreement.  All claims and disputes (excluding claims for injunctive or other equitable relief as set forth below) in connection with the Terms or the use of any product or service provided by the Company that cannot be resolved informally or in small claims court shall be resolved by binding arbitration on an individual basis under the terms of this Arbitration Agreement.  Unless otherwise agreed to, all arbitration proceedings shall be held in English.  This Arbitration Agreement applies to you and the Company, and to any subsidiaries, affiliates, agents, employees, predecessors in interest, successors, and assigns, as well as all authorized or unauthorized users or beneficiaries of services or goods provided under the Terms."
const para47 = "Notice Requirement and Informal Dispute Resolution. Before either party may seek arbitration, the party must first send to the other party a written Notice of Dispute (“Notice”) describing the nature and basis of the claim or dispute, and the requested relief.  A Notice to the Company should be sent to: 123 Main Street, Mountain View, California 94041.  After the Notice is received, you and the Company may attempt to resolve the claim or dispute informally.  If you and the Company do not resolve the claim or dispute within thirty (30) days after the Notice is received, either party may begin an arbitration proceeding.  The amount of any settlement offer made by any party may not be disclosed to the arbitrator until after the arbitrator has determined the amount of the award, if any, to which either party is entitled."
const para48 = "Arbitration Rules.  Arbitration shall be initiated through the American Arbitration Association (“AAA”), an established alternative dispute resolution provider (“ADR Provider”) that offers arbitration as set forth in this section.  If AAA is not available to arbitrate, the parties shall agree to select an alternative ADR Provider.  The rules of the ADR Provider shall govern all aspects of the arbitration, including but not limited to the method of initiating and/or demanding arbitration, except to the extent such rules are in conflict with the Terms.  The AAA Consumer Arbitration Rules (“Arbitration Rules”) governing the arbitration are available online at www.adr.org or by calling the AAA at 1-800-778-7879.  The arbitration shall be conducted by a single, neutral arbitrator.  Any claims or disputes where the total amount of the award sought is less than Ten Thousand U.S. Dollars (US $10,000.00) may be resolved through binding non-appearance-based arbitration, at the option of the party seeking relief.  For claims or disputes where the total amount of the award sought is Ten Thousand U.S. Dollars (US $10,000.00) or more, the right to a hearing will be determined by the Arbitration Rules.  Any hearing will be held in a location within 100 miles of your residence, unless you reside outside of the United States, and unless the parties agree otherwise.  If you reside outside of the U.S., the arbitrator shall give the parties reasonable notice of the date, time and place of any oral hearings. Any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction.  If the arbitrator grants you an award that is greater than the last settlement offer that the Company made to you prior to the initiation of arbitration, the Company will pay you the greater of the award or $2,500.00.  Each party shall bear its own costs (including attorney’s fees) and disbursements arising out of the arbitration and shall pay an equal share of the fees and costs of the ADR Provider."
const para49 = "Additional Rules for Non-Appearance Based Arbitration.  If non-appearance based arbitration is elected, the arbitration shall be conducted by telephone, online and/or based solely on written submissions; the specific manner shall be chosen by the party initiating the arbitration.  The arbitration shall not involve any personal appearance by the parties or witnesses unless otherwise agreed by the parties."
const para50 = "Time Limits.  If you or the Company pursue arbitration, the arbitration action must be initiated and/or demanded within the statute of limitations (i.e., the legal deadline for filing a claim) and within any deadline imposed under the AAA Rules for the pertinent claim."
const para51 = "Waiver of Jury Trial.  THE PARTIES HEREBY WAIVE THEIR CONSTITUTIONAL AND STATUTORY RIGHTS TO GO TO COURT AND HAVE A TRIAL IN FRONT OF A JUDGE OR A JURY, instead electing that all claims and disputes shall be resolved by arbitration under this Arbitration Agreement.  Arbitration procedures are typically more limited, more efficient and less costly than rules applicable in a court and are subject to very limited review by a court.  In the event any litigation should arise between you and the Company in any state or federal court in a suit to vacate or enforce an arbitration award or otherwise, YOU AND THE COMPANY WAIVE ALL RIGHTS TO A JURY TRIAL, instead electing that the dispute be resolved by a judge."
const para52 = "Waiver of Class or Consolidated Actions.  ALL CLAIMS AND DISPUTES WITHIN THE SCOPE OF THIS ARBITRATION AGREEMENT MUST BE ARBITRATED OR LITIGATED ON AN INDIVIDUAL BASIS AND NOT ON A CLASS BASIS, AND CLAIMS OF MORE THAN ONE CUSTOMER OR USER CANNOT BE ARBITRATED OR LITIGATED JOINTLY OR CONSOLIDATED WITH THOSE OF ANY OTHER CUSTOMER OR USER.  "
const para53 = "Confidentiality.  All aspects of the arbitration proceeding, including but not limited to the award of the arbitrator and compliance therewith, shall be strictly confidential.  The parties agree to maintain confidentiality unless otherwise required by law.  This paragraph shall not prevent a party from submitting to a court of law any information necessary to enforce this Agreement, to enforce an arbitration award, or to seek injunctive or equitable relief."
const para54 = "Severability.  If any part or parts of this Arbitration Agreement are found under the law to be invalid or unenforceable by a court of competent jurisdiction, then such specific part or parts shall be of no force and effect and shall be severed and the remainder of the Agreement shall continue in full force and effect."
const para55 = "Right to Waive.  Any or all of the rights and limitations set forth in this Arbitration Agreement may be waived by the party against whom the claim is asserted.  Such waiver shall not waive or affect any other portion of this Arbitration Agreement."
const para56 = "Survival of Agreement.  This Arbitration Agreement will survive the termination of your relationship with the Company.  "
const para57 = "Small Claims Court.  Notwithstanding the foregoing, either you or the Company may bring an individual action in small claims court."
const para58 = "Emergency Equitable Relief.  Notwithstanding the foregoing, either party may seek emergency equitable relief before a state or federal court in order to maintain the status quo pending arbitration.  A request for interim measures shall not be deemed a waiver of any other rights or obligations under this Arbitration Agreement."
const para59 = "Claims Not Subject to Arbitration.  Notwithstanding the foregoing, claims of defamation, violation of the Computer Fraud and Abuse Act, and infringement or misappropriation of the other party’s patent, copyright, trademark or trade secrets shall not be subject to this Arbitration Agreement."
const para60 = "Courts.  In any circumstances where the foregoing Arbitration Agreement permits the parties to litigate in court, the parties hereby agree to submit to the personal jurisdiction of the courts located within Santa Clara County, California, for such purpose "
const para61 = "Future Changes to Arbitration Agreement. Notwithstanding any provision in these Terms to the contrary, Company agrees that if it makes any future change to this Arbitration Agreement (other than a change to the Notice Address) while you are a user of the Site, you may reject any such change by sending Company written notice within thirty (30) calendar days of the change to the notice address provided below. By rejecting any future change, you are agreeing that you will arbitrate any dispute between us in accordance with the language of this Arbitration Agreement as of the date you first accepted these Terms of Use (or accepted any subsequent changes to these Terms of Use)."
const para62 = "User Disputes: You agree that you are solely responsible for your interactions with any other user in connection with the Site and Company will have no liability or responsibility with respect thereto. Company reserves the right, but has no obligation, to become involved in any way with disputes between you and any other user of the Site."
const para63 = "Export: The Site may be subject to U.S. export control laws and may be subject to export or import regulations in other countries. You agree not to export, reexport, or transfer, directly or indirectly, any U.S. technical data acquired from Company, or any products utilizing such data, in violation of the United States export laws or regulations. "
const para64 = "Disclosures.  Company is located at the address below. If you are a California resident, you may report complaints to the Complaint Assistance Unit of the Division of Consumer Product of the California Department of Consumer Affairs by contacting them in writing at 400 R Street, Sacramento, CA 95814, or by telephone at (800) 952-5210."
const para65 = "Electronic Communications.  The communications between you and Company use electronic means, whether you use the Site or send us emails, or whether Company posts notices on the Site or communicates with you via email. For contractual purposes, you (a) consent to receive communications from Company in an electronic form; and (b) agree that all terms and conditions, agreements, notices, disclosures, and other communications that Company provides to you electronically satisfy any legal requirement that such communications would satisfy if it were be in a hardcopy writing. The foregoing does not affect your non-waivable rights."
const para66 = "Entire Terms. These Terms constitute the entire agreement between you and the Company and govern your use of the Site, superseding any prior agreements between you and the Company with respect to the Site. These Terms will be governed by the laws of the State of California without regard to its conflict of law provisions. With respect to any disputes or claims not subject to arbitration, as set forth above, you and the Company agree to submit to the personal and exclusive jurisdiction of the state and federal courts located within San Francisco County, California. The failure of the Company to exercise or enforce any right or provision of these Terms will not constitute a waiver of such right or provision. If any provision of these Terms is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties’ intentions as reflected in the provision, and the other provisions of these Terms remain in full force and effect. You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Site or these Terms must be filed within one (1) year after such claim or cause of action arose or be forever barred. A printed version of this agreement and of any notice given in electronic form will be admissible in judicial or administrative proceedings based upon or relating to this agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. You may not assign this Terms without the prior written consent of the Company, but the Company may assign or transfer these Terms, in whole or in part, without restriction. The section titles in these Terms are for convenience only and have no legal or contractual effect. Notices to you may be made via either email or regular mail. The Site may also provide notices to you of changes to these Terms or other matters by displaying notices or links to notices generally on the Site."
const para67 = "Copyright/Trademark Information.  Copyright © 2021 Hyperscale. All rights reserved.  All trademarks, logos and service marks (“Marks”) displayed on the Site are our property or the property of other third parties. You are not permitted to use these Marks without our prior written consent or the consent of such third party which may own the Marks."
const para68 = "Contact Information for Notice:"
const para69 = ""



const links = [
	'https://www.twitter.com/HyperscaleFund',
	'https://discord.gg/7CGPQ8fWHt',
	'https://airtable.com/shrLFCXD7BQXUg97K',
]

const Terms = () => (
	<div>
		<div className="bg-no-repeat bg-cover bg-[#1602AS] pb-16 px-6 md:px-10" style={{ backgroundImage : "url('./section1/background.svg')" }}>
			<Header />
			<div className="bg-[#160A2F] md:p-8 relative">
				<div className="container mx-auto pt-8 xl:px-32">		
					<div className="container mx-auto bg-[#EBE8E3] rounded py-24 px-4 sm:px-10 xl:px-32">
						<h2 className="font-redrose text-5xl pb-12">Terms of Use</h2>
						<div className="my-6">{para1}</div>
						<div className="my-6">{para2}</div>
						<div className="my-6">{para3}</div>
						<div className="my-6">{para4}</div>
						<div className="my-6">{para5}</div>
						<div className="my-6">{para6}</div>
						<div className="my-6">{para7}</div>
						<div className="my-6">{para8}</div>
						<div className="my-6">{para9}</div>
						<div className="my-6">{para10}</div>
						<div className="my-6">{para11}</div>
						<div className="my-6">{para12}</div>
						<div className="my-6">{para13}</div>
						<div className="my-6">{para14}</div>
						<div className="my-6">{para15}</div>
						<div className="my-6">{para16}</div>
						<div className="my-6">{para19}</div>
						<div className="my-6">{para20}</div>
						<div className="my-6">{para21}</div>
						<div className="my-6">{para22}</div>
						<div className="my-6">{para23}</div>
						<div className="my-6">{para24}</div>
						<div className="my-6">{para25}</div>
						<div className="my-6">{para26}</div>
						<div className="my-6">{para27}</div>
						<div className="my-6">{para28}</div>
						<div className="my-6">{para29}</div>
						<div className="my-6">{para30}</div>
						<div className="my-6">{para31}</div>
						<div className="my-6">{para32}</div>
						<div className="my-6">{para33}</div>
						<div className="my-6">{para34}</div>
						<div className="my-6">{para35}</div>
						<div className="my-6">{para36}</div>
						<div className="my-6">{para37}</div>
						<div className="my-6">{para38}</div>
						<div className="my-6">{para39}</div>
						<div className="my-6">{para40}</div>
						<div className="my-6">{para41}</div>
						<div className="my-6">{para42}</div>
						<div className="my-6">{para43}</div>
						<div className="my-6">{para44}</div>
						<div className="my-6">{para45}</div>
						<div className="my-6">{para46}</div>
						<div className="my-6">{para47}</div>
						<div className="my-6">{para48}</div>
						<div className="my-6">{para49}</div>
						<div className="my-6">{para50}</div>
						<div className="my-6">{para51}</div>
						<div className="my-6">{para52}</div>
						<div className="my-6">{para53}</div>
						<div className="my-6">{para54}</div>
						<div className="my-6">{para55}</div>
						<div className="my-6">{para56}</div>
						<div className="my-6">{para57}</div>
						<div className="my-6">{para58}</div>
						<div className="my-6">{para59}</div>
						<div className="my-6">{para60}</div>
						<div className="my-6">{para61}</div>
						<div className="my-6">{para62}</div>
						<div className="my-6">{para63}</div>
						<div className="my-6">{para64}</div>
						<div className="my-6">{para65}</div>
						<div className="my-6">{para66}</div>
						<div className="my-6">{para67}</div>
						<div className="my-6">{para68}</div>
						<div className="my-6">{para69}</div>
					</div>
				</div>
			</div>
		</div>
		<Footer />
	</div>
)

export default Terms
